"""add cascade

Revision ID: 385b676965a7
Revises: c1e4011d31f4
Create Date: 2023-06-24 16:24:10.852015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385b676965a7'
down_revision = 'c1e4011d31f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('backlogs_user_id_fkey', 'backlogs', type_='foreignkey')
    op.create_foreign_key(None, 'backlogs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('completegames_user_id_fkey', 'completegames', type_='foreignkey')
    op.create_foreign_key(None, 'completegames', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'completegames', type_='foreignkey')
    op.create_foreign_key('completegames_user_id_fkey', 'completegames', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'backlogs', type_='foreignkey')
    op.create_foreign_key('backlogs_user_id_fkey', 'backlogs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
